extract:
  # This step pulls raw data from each resource
  fitbit:
    start_date: '2021-10-01'
    end_date: 'today'
    endpoints:
      activities/heart:
        output_path: 'data/extract/fitbit/hearts.csv'
      activities/distance:
        output_path: 'data/extract/fitbit/distances.csv'
      body/weight:
        output_path: 'data/extract/fitbit/weights.csv'
      body/fat:
        output_path: 'data/extract/fitbit/fats.csv'
      body/bmi:
        output_path: 'data/extract/fitbit/bmis.csv'
      sleep:
        output_path: 'data/extract/fitbit/sleeps.csv'
    creds_path: 'creds.yml'
    creds_key: 'fitbit'
  plaid:
    # Plaid's agreement with Capital One only permits downloading the last 90 days of authorization by the user
    # Further institution-specific limitations: https://dashboard.plaid.com/oauth-guide
    start_date: '2022-03-16'
    end_date: 'today'
    endpoints:
      # Barclaycard is actually a distinct entity from Barclays. Plaid doesn't enable access to the former.
      aspiration:
        output_path: 'data/extract/plaid/aspiration.csv'
      chase:
        output_path: 'data/extract/plaid/chase.csv'
      capital_one:
        output_path: 'data/extract/plaid/capital_one.csv'
    creds_path: 'creds.yml'
    creds_key: 'plaid'
  splitwise:
    start_date: '2022-11-01'
    end_date: 'today'
    output_path: 'data/extract/splitwise/splitwise.csv'
    creds_path: 'creds.yml'
    creds_key: 'splitwise'
  strava:
    start_date: '2021-10-01'
    end_date: 'today' # This actually isn't configurable. StravaIO just extracts up to the present day
    output_path: 'data/extract/strava/activities.csv'
    creds_path: 'creds.yml'
    creds_key: 'strava'
transform:
  skis:
    # Start and end of the season
    start_date: '2022-11-01'
    end_date: '2023-06-01'
    output_path: 'data/transform/skis.csv'
  vitals:
    start_date: '12 weeks ago'
    end_date: 'today'
    output_path: 'data/transform/vitals.csv'
  transactions:
    start_date: '12 weeks ago'
    end_date: 'today'
    output_path: 'data/transform/transactions.csv'
